import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/contexts/appContext";
import NextAuthSessionProvider from "@/providers/NextAuthProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <AppContextProvider>
            {children}
          </AppContextProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
